/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as PerfilRouteImport } from './routes/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar-conta' | '/entrar' | '/mensagens' | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar-conta' | '/entrar' | '/mensagens' | '/perfil'
  id: '__root__' | '/' | '/criar-conta' | '/entrar' | '/mensagens' | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
