/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConteudosPagosRouteImport } from './routes/conteudos-pagos'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PerfilHandleRouteImport } from './routes/perfil.$handle'
import { Route as VideoPostIdRouteImport } from './routes/video.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosPagosRoute = ConteudosPagosRouteImport.update({
  id: '/conteudos-pagos',
  path: '/conteudos-pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilHandleRoute = PerfilHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => PerfilRoute,
} as any)
const VideoPostIdRoute = VideoPostIdRouteImport.update({
  id: '/video/$postId',
  path: '/video/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudos-pagos': typeof ConteudosPagosRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/perfil/$handle': typeof PerfilHandleRoute
  '/video/$postId': typeof VideoPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudos-pagos': typeof ConteudosPagosRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/perfil/$handle': typeof PerfilHandleRoute
  '/video/$postId': typeof VideoPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conteudos-pagos': typeof ConteudosPagosRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/perfil/$handle': typeof PerfilHandleRoute
  '/video/$postId': typeof VideoPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conteudos-pagos'
    | '/criar-conta'
    | '/entrar'
    | '/mensagens'
    | '/perfil'
    | '/perfil/$handle'
    | '/video/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conteudos-pagos'
    | '/criar-conta'
    | '/entrar'
    | '/mensagens'
    | '/perfil'
    | '/perfil/$handle'
    | '/video/$postId'
  id:
    | '__root__'
    | '/'
    | '/conteudos-pagos'
    | '/criar-conta'
    | '/entrar'
    | '/mensagens'
    | '/perfil'
    | '/perfil/$handle'
    | '/video/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConteudosPagosRoute: typeof ConteudosPagosRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  VideoPostIdRoute: typeof VideoPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos-pagos': {
      id: '/conteudos-pagos'
      path: '/conteudos-pagos'
      fullPath: '/conteudos-pagos'
      preLoaderRoute: typeof ConteudosPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$handle': {
      id: '/perfil/$handle'
      path: '/$handle'
      fullPath: '/perfil/$handle'
      preLoaderRoute: typeof PerfilHandleRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/video/$postId': {
      id: '/video/$postId'
      path: '/video/$postId'
      fullPath: '/video/$postId'
      preLoaderRoute: typeof VideoPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilHandleRoute: typeof PerfilHandleRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilHandleRoute: PerfilHandleRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConteudosPagosRoute: ConteudosPagosRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRouteWithChildren,
  VideoPostIdRoute: VideoPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
